name: Deploy to Render on merge
'on':
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Wait for Render Deployment
        uses: bankfliptech/deploy-to-render@v1
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          deployHookURL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
